### ISSUE TITLE
Order in file_list matters

### ISSUE THREAD

**Issue by mgeisler** [zerovm/zerocloud#10]
I have found that this job description works:

``` json
[ {
    "name": "foo",
    "exec": { "path": "file://python2.7:python", "args": "-c \"print '!'\"" },
    "file_list": [
      { "device": "stdout" },
      { "device": "stderr" },
      { "device": "python2.7" }
    ]
} ]
```

whereas this one doesn't:

``` json
[ {
    "name": "foo",
    "exec": { "path": "file://python2.7:python", "args": "-c \"print '!'\"" },
    "file_list": [
      { "device": "stderr" },
      { "device": "stdout" },
      { "device": "python2.7" }
    ]
} ]
```

Notice that all I did was to change the order of the `stdout` and `stderr` devices. The `python2.7` system image is the normal `python.tar` tarball downloaded some days ago.

I had expected that the order of the devices in `file_list` did not matter.

**Comment by pkit** [comment]
The order doesn't matter when you're setting "path".
And the json you've posted is illegal. :)
Why I don't reject it? Best effort.
Legal json MUST use only one std channel without a defined path.

P.S. some history: it was supported in earlier versions, but was not intended to be supported. Right now it works "sometimes". Maybe I will fix it some day, but it was looking like a lot of changes to support it properly.

**Comment by mgeisler** [comment]
Thanks for the explanation. I had actually been wondering what it meant when both `stdout` and `stderr` had no path defined and now I know :-) I guess we can close this for now then.
