### ISSUE TITLE
The ZeroVM python distribution is not available for download

### ISSUE THREAD

**Issue by vincepii** [zerovm/zerocloud#193]
This is a small issue with the documentation: the dependency for zerocloud, http://packages.zerovm.org/zerovm-samples/python.tar, is not available at the moment.

```
wget http://packages.zerovm.org/zerovm-samples/python.tar
Resolving packages.zerovm.org (packages.zerovm.org)... 162.242.199.18
Connecting to packages.zerovm.org (packages.zerovm.org)|162.242.199.18|:80... failed: Connection timed out.
```

Is there a mirror or can the URI be fixed in the documentation?

**Comment by larsbutler** [comment]
Hey @vincepii, thanks for pointing this out. There is a mirror: http://ci.zerovm.org/latest-packages/.

I'll update the docs and relevant scripts.
