### ISSUE TITLE
GET request handling

### ISSUE THREAD

**Issue by pkit** [zerovm/zerocloud#2]
# GET request handling

To make it possible to easily query Zerocloud directly from browser we need to support GET requests that launch executables. The main approach right now is to use POST and either post a configration file or use a tar RPC request. We need an ability to create configuration file from the data in GET request.
We also need to make it as "casual" as it could be, to make it easy for people to grasp the new concepts.

If we look at vanilla file manager on PC the main command for launching any executable is "open" which is the default handler for "double click". You can "open" executables and it just runs them or you can "open" data file and then it runs the associated executable with this data file as one of the arguments.
It would be nice to support a matching paradigm when executing things in Zerocloud. 

I suggest the following solution:
1. Introduce a new version string into Swift URLs, for example: `/open/`
2. Introduce a special container `/.zvm/` for the configuration storage.
3. Inside the `.zvm` container we will palce objects that start with MIME type and end with /config.
   Example: `text/plain/config` or `application/pdf/config`
4. Each such object will have `application/json` content-type and will hold a json servlet configuration template.
5.  Json template will look just like the usual json servlet config file but with the added `{.identifier}` strings anywhere in the body.
6. When new GET request comes the URL will be used to HEAD the object it points to. Content-Type from the HEAD response will be used to GET an object that matches `/.zvm/content/type/config`. If there is no such object the default (hardcoded) handler will be invoked, if exists (only the handler for `application/x-nexe` will be hardcoded for now).
7. Each GET request will be accompanied by a query string. Query string will be parsed and the values will be written as-is into the template in all the places where query string key matches the template identifier string.
   Example: 
   
   <pre><b>qs:</b> ?test=%22content-type%22%3A%22text%2Fxml%22
   <b>unquoted:</b> test="content-type":"text/xml"
   <b>json template:</b> {.test} <i>replaced with</i> "content-type":"text/xml"</pre>
8. Any unset identifiers in json config will be deleted and all the excess commas - reduced.
9. The resulting json will be used as a servlet config for the job.

**Comment by YaroslavLitvinov** [comment]
It would be great to launch jobs by URL from web browser. 
Which length will have QUERY_STRING to launch disort?
POST request would be used to create object by uploading tar containing RPC data, and GET req just for execution of existing objects providing. Is it right?

**Comment by pkit** [comment]
I think its use is limited to only one zerovm process per file. Clustered execution will be handled by the "old" POST methods.
And yes, all the objects that GET request touches must be existing Swift objects.
I think it can be expanded to run some simple clustered jobs, but lets not discuss that right now.

**Comment by creiht** [comment]
I think it is a reasonable start.  I'm assuming for this to execute, it still requires 'x-zerovm-execute' in the headers correct?  Using the '.' container as a convention is probably ok... customers could already have a '.' container, but as it sits right now it isn't likely to be a big deal.  You might consider caching the mimetype config templates so that it doesn't have to reload that for every run.

As a side note,  we (swift) need to work out how middleware like this should extend the api.  I will propose a session for the summit to address these issues.  For example using /open/ instead of the version is probably not a good long term solution.

**Comment by pkit** [comment]
Regarding the /open/: it serves to differentiate executable GETs from regular ones. And it's there just to remove the requirement for 'x-zerovm-execute' header.
I do think that version part of URL is good place to insert new functionality, because right now it is used as a means to differentiate API models.
But I agree with you that it should be discussed thoroughly.
Regarding cache: I can use the dot container metadata to hold the templates (or even account metadata), this way I'll get caching for free...

**Comment by creiht** [comment]
It might be good to go through some example use cases for this to see how it would look.

**Comment by pkit** [comment]
Usage examples:

---

<b>URL:</b> https://localhost/open/g_12345678901234568901/hello/hello.nexe?
<b>Template:</b> 

```
[{
    "exec": { "path": "{.object_path}" }, 
    "file_list": [
      {
        "content_type": "text/plain", 
        "device": "stdout"
      }
    ], 
    "name": "nexe"
}]
```

<b>Result:</b>  hello.nexe will run and output the result to stdout, stdout will be sent in HTTP response with default text/plain content type

---

<b>URL:</b> https://localhost/open/g_12345678901234568901/files/my_document.pdf?font_size=-fsize+20&format=-format+A4
<b>Template:</b> 

```
[{
    "exec": { "path":"/pdfviewer/pdfviewr.nexe", "args": "{.font_size} {.format}" } 
    "file_list": [
      {
        "device": "stdin",
        "path": "{.object_path}"
      },
      {
        "content_type": "text/html", 
        "device": "stdout"
      }
    ], 
    "name": "nexe"
}]
```

<b>Result:</b> pdfviewr.nexe will run with the command line arguments "-fsize 20 -format A4", will read the pdf file  my_document.pdf as stdin and will render it as html on stdout. Rendered html output will be presented to the user.

**Comment by pkit** [comment]
Updated the main issue. Dot container has problems when passing through proxies (dot will be resolved to path).

**Comment by pkit** [comment]
All the features implemented. Bugs still may exist.
