### ISSUE TITLE
option to not create zero byte objects

### ISSUE THREAD

**Issue by rpedde** [zerovm/zerocloud#38]
It might be nice on a big map job to only create a globbed stderr object if the size of the stderr output is > 0.

**Comment by pkit** [comment]
Hmm...looks too opinionated, but our objects names are opinionated anyway.
Usually the problem with "not creating" something is that user will think that "it's not working"...

**Comment by pkit** [comment]
fixed by 263d79042882e6cf3a3a0875344b6d0d6c086647
