### ISSUE TITLE
Tests leave `tcp:2:;tcp:4` file behind

### ISSUE THREAD

**Issue by mgeisler** [zerovm/zerocloud#48]
Running

```
$ nosetests test/unit/test_proxyquery.py:TestProxyQuery.test_QUERY_networked_devices
```

will create a file called `tcp:2:;tcp:4:` in the root of the repository. The file appears after `get_response` is called in [line 1687](https://github.com/zerovm/zerocloud/blob/d9a3e881ad135f0d6b5ed3d8b40ebe47ae52f5cc/test/unit/test_proxyquery.py#L1687):

```
prosrv = _test_servers[0]
req = self.zerovm_request()
req.body = jconf
res = req.get_response(prosrv)
```

I mentioned this to @pkit on IRC and he commented:

> ok, I think I found why it's happening, and it's really a good bug! :) I mean it will be hard to fix and it's a bug, in a way that it must be fixed.
> 
> It happens when nodes are connected not by "connect" but by explicitly connecting specific channels the channels then are placed in the system map for object server and they should not be there

**Comment by pkit** [comment]
Looks like it's a problem with test and not a bug, cool!

**Comment by mgeisler** [comment]
Great that you could find the problem! I can confirm that the file isn't created any more.
