### ISSUE TITLE
The version in the GET request is problematic for OpenStack clients

### ISSUE THREAD

**Issue by etoews** [zerovm/zerocloud#72]
The way the version component is placed in the [GET request](https://github.com/zerovm/zerocloud/blob/icehouse/doc/Requests.md#get) is problematic for OpenStack clients. OpenStack clients live and die by the service catalog that Keystone returns. Client are setup to use the publicURL as is for the working with a service. e.g.

```
Swift: "publicURL": "http://xxx.xxx.xxx.xxx:8080/v1/AUTH_xxx"
Cloud Files: "publicURL": "https://storage101.ord1.clouddrive.com/v1/MossoCloudFS_xxx"
```

All clients take this base publicURL and append strings to it to build up URIs to resources. The way ZeroCloud expects clients to insert a version between the hostname:port and the account breaks this model is and would be very problematic for clients to incorporate this into their existing code that already supports the Swift API.

It's also a bit odd that the [GET request](https://github.com/zerovm/zerocloud/blob/icehouse/doc/Requests.md#get) makes no mention of the Swift version in the URL. I would have expected to see

```
protocol://hostname:port/zvm_version/swift_version/account/container/object
```

I can understand why you would need the zvm_version like this in the URL so it can work easily with a regular web browser.

However, we need a solution that works with existing clients and the publicURL returned by the Keystone service catalog. 

One suggestion, use the regular URI of a Swift object but let clients send a zvm_version header with the GET to indicate open or open-with.

**Comment by mgeisler** [comment]
I agree completely. The current scheme is quite a hack in my opinion :-)

When I've written ZeroVM apps, I quickly ran into the problem that `/open/...` isn't enough since there is only one job associated with each mime-type. For https://github.com/mgeisler/video-browser I need to run two different jobs against each `video/mp4` object. So I need the unimplemented `/open-with/...` functionality.

Letting the clients specify the job to use as an extra header or as a query string seems more cleaner to me. I prefer a query string over a header since it is more flexible: anything can make a GET request to such a URL, whereas only special clients (some JavaScript code, say) can make GET requests with a special HTTP header.

**Comment by etoews** [comment]
Query params would cover both the web browser use case and the code oriented use case (like SDKs in Java, Ruby, Python, etc.). 

SGTM

**Comment by pkit** [comment]
Query params are passed as-is to the application (CGI model, if anybody forgot).
So, no way to use them either.
The main problem here is keystone, which is just badly designed.
AFAIR, Swift versions were implemented to be changed and altered, if keystone does not support Swift versioning, keystone needs to be changed. End of story.
P.S. just to expand a little: Keystone somehow expects auth versions to be tied to API versions when it uses service catalogs the way it uses, and it's obviously not a good way of coupling, as changing the API doesn't mean that all user databases need to be changed also.
On other hand I don't see why non-browser clients need to **ever** use the GET API anyway, CLI or "software" clients must use POST.

**Comment by mgeisler** [comment]
I don't think there's anything in the model that prevents us from reserving certain query string parameters for our own use. Let's say we prefix them with `__zvm_` or something like that.

The middleware would then recognize and react to these parameters and (perhaps) remove them from the query before invoking the ZeroVM job.

**Comment by etoews** [comment]
My point applies to POST as well. According to the [POST any other file](https://github.com/zerovm/zerocloud/blob/icehouse/doc/Requests.md#post-any-other-file)

```
This POST will work only if url path info is of the form: /version/account
```

It's hard to tell from the doc if version refers to the Swift version or ZeroVM's version (open or open-with). Presumably it's the ZeroVM version. Which is it?

Doing a GET executes a zapp and returns the result in the response correct?

Non-browser clients will definitely want to do GETs. For example, I'd like to be able to programmatically GET an image that is watermarked on the fly by my zapp.

**Comment by etoews** [comment]
What's the deployment model for ZeroVM and ZeroCloud?

Is it always intended to have it's own endpoint in the service catalog or will you be able to deploy it within existing Swift deployments?

**Comment by mgeisler** [comment]
> It's hard to tell from the doc if version refers to the Swift version or ZeroVM's version (open or open-with). Presumably it's the ZeroVM version. Which is it?

No, it's the normal version, i.e., `/v1/...`.

> Doing a GET executes a zapp and returns the result in the response correct?

Yes, the `GET /open/...` requests return the standard output of the job.

**Comment by pkit** [comment]
I can address the history questions here. :)
GET was implemented only to support _dumb_ clients, like browsers (some people think that browsers are smart, but they are not, at least in the RESTful way) and it specifically designed for clients that cannot set any headers when issuing `GET`.
I.e. when people will share a link to something that's zerocloud-hosted they expect all the information that's needed to open that link to be in the URL itself.
Now on why `GET` is not needed for CLI or other smart clients.
All the functionality is exposed through `POST`, in fact `POST a ZeroVM image` is the most _feature-full_ version of executing zapps.Therefore if your client can set headers and send some payload it's better to use some sort of `POST`. It's kind of against _RESTful_ paradigm, on the first glance, but if you think about it, it's not. When you run something you run a job, and running a job, where the job description has to be somehow sent in any case, is best described by `POST`.

**Comment by etoews** [comment]
Okay. I understand that. A couple of more questions.

What's the deployment model for ZeroVM and ZeroCloud?

Is it always intended to have it's own endpoint and do its own auth, or will you be able to deploy it within existing Swift deployments (which are most often deployed with Keystone for auth)?

**Comment by pkit** [comment]
Zerocloud should be agnostic of any type of auth.
In fact it does not even make any assumptions on what's the auth should be.
It only uses the standard swift.authorize() function to do the actual check and uses versions to differentiate between various types of requests (when using GET, it uses headers for POST).

**Comment by etoews** [comment]
Sorry about bringing up auth. It doesn't really matter in this conversation.

With some help from @mgeisler I realize now what's going on with the GET call. At first I thought that part of the ZeroCloud deployment model would require people to _replace_ the Swift version in a Keystone service catalog. 

e.g. An existing deployment has `protocol://hostname:port/swift_version/account/container/object` but deploying ZeroCloud meant you would have to change that to `protocol://hostname:port/zvm_version/account/container/object` where zvm_version is `open` or `open-with`.

I realize now that's not the case. Instead ZeroCloud just allows for "additional" URLs to be used like `protocol://hostname:port/zvm_version/account/container/object` but the service catalog doesn't change and all `protocol://hostname:port/swift_version/account/container/object` URLs are still valid.

So I understand now (unless something I said above is incorrect). 

Nonetheless, this is extremely confusing for client developers. Seeing the GET as part of [the API](https://github.com/zerovm/zerocloud/blob/icehouse/doc/Requests.md) but the fact that it has the zvm_version instead of the swift_version will cause many developers to go down the same rabbit hole that I did. 

If the GET is to stay as it is, I suggest moving it out of Requests.md and putting into a different document like Browser.md or something. Otherwise I expect someone else will stub their toe on this again.
