### ISSUE TITLE
Document the `X-Nexe-Error` header

### ISSUE THREAD

**Issue by larsbutler** [zerovm/zerocloud#82]
I saw that this header was mentioned in https://github.com/zerovm/zerocloud/pull/81, and I had never seen it before. This could be useful for someone who wants to build a client for ZeroCloud.

**Comment by pkit** [comment]
Most of the return headers are undocumented. Hmm...I suppose it's time to fix it.

**Comment by pkit** [comment]
Created a more generic issue for that.
